let instruction_text = {
    'general': [
        `<p>Once you are seated comfortably at the screen, position your fingers on the keyboard such that your left index finger is resting on the <b>f</b> key and your right index finger on the <b>j</b> key. For the remainder of the experiment, the <b>f</b> key will correspond with <b>left</b> and the <b>j</b> key with <b>right</b>.<br><br>Note that this will be the case for every block of trials – whether you are responding to the car’s rear light signals, the road signs, or a combination of the two.<br><br>When looking at the screen you do not need to direct your eyes anywhere in particular- simply imagine that you are following a car that is driving on the highway.<br><br>Press spacebar when you are ready to continue</p>`
     ],
    'signal': [
        `<p>When this block of trials begins, the left or right rear light on the back of the car will be illuminated to communicate the direction in which the car ahead is signalling to turn.<br>Your task is to respond to this signal as <b>quickly and as accurately as possible.</b><br><br>If you make the correct response (ex. Indicate left for a left turn), you will receive no feedback; however, if you make the wrong response (ex. Indicate right for a left turn) or fail to respond at all, you will be honked at.<br><br>Despite this, please try to maintain your focus for the remainder of the trials and continue responding as quickly and accurately as you can.<br><br>Press spacebar to begin the block, as well as to initiate each trial.</p>`
    ],
    'sign': [
        `<p>When this block of trials begins, you will see an arrow appear in one of the three designated road signs at the top of the screen.<br>Your task is to indicate which way the sign is pointing as <b>quickly and as accurately as possible.</b><br><br>If you make the correct response (ex. Indicate left for a leftward pointing sign), you will receive no feedback; however, if you make the wrong response (ex. Indicate right for a leftward pointing sign) or fail to respond, you will be honked at.<br><br>Despite this, please try to maintain your focus for the remainder of the trials and continue responding as quickly and accurately as you can.<br><br>Press spacebar to begin the block, as well as to initiate each trial.</p>`
    ],
    'mixed': [
        `<p>When this block of trials begins, you will be faced with decisions about which direction the car is turning, or the road sign is pointing.<br>This combines the tasks you did on the two previous blocks – though you will not be responding simultaneously.<br><br>Again, if you answer correctly, you will receive no feedback; however, if you make the wrong response or fail to respond you will receive feedback in the form of an audible car horn.<br><br>Despite this, please try to maintain your focus for the remainder of the trials and continue responding as quickly and accurately as you can.<br><br>Press spacebar to begin the block, as well as to initiate each trial.</p>`
    ]
}

